// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAClomI-cM8Wdr1SIIpb_-UtoveO1sPNE',
    appId: '1:186756439743:android:2b8f31f0cae8bfbbb8300a',
    messagingSenderId: '186756439743',
    projectId: 'myfirstappforhungarymed',
    storageBucket: 'myfirstappforhungarymed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3NtmJPNyDfnBc6vPNGgp4eKMGIPDX7eQ',
    appId: '1:186756439743:ios:12d52b1044ef7df7b8300a',
    messagingSenderId: '186756439743',
    projectId: 'myfirstappforhungarymed',
    storageBucket: 'myfirstappforhungarymed.firebasestorage.app',
    iosClientId: '186756439743-f02f2scv67p8sq3bfe83slb7lj636bc2.apps.googleusercontent.com',
    iosBundleId: 'com.example.europemedstudentcommunityapp',
  );
}
